export const rankName = {
    points: '得分',
    rebounds: '籃板',
    def_rebounds: '後場籃板',
    off_rebounds: '前場籃板',
    assists: '助攻',
    steals: '抄截',
    blocks: '阻攻',
    turnovers: '失誤',
    minutes: '上場時間',
    personal_fouls: '犯規',
    tech_fouls: '技術犯規',
    foulouts: '犯滿',
    field_goals_made: '投籃命中數',
    field_goals_att: '投籃出手',
    field_goals_pct: '投籃命中率',
    three_points_made: '三分命中數',
    three_points_att: '三分出手',
    three_points_pct: '三分命中率',
    free_throws_made: '罰球命中數',
    free_throws_att: '罰球出手',
    free_throws_pct: '罰球命中率',
    two_points_made: '兩分命中數',
    two_points_att: '兩分出手',
    two_points_pct: '兩分命中率',
}